### ISSUE TITLE
Is this addon still active?

### ISSUE THREAD

**Issue by AxaliaN** [watchedsyncforkodi/service.watchedsync#10]
Hiya,

I have requested registration on November 22nd but so far haven't heard anything back. Is this system still active?

Regards,

Michel Maas

**Comment by watchedsyncforkodi** [comment]
Yes service is still active. Registration request backlog has been cleared. 

Thanks

**Comment by AxaliaN** [comment]
Hey hey,

it seems mine was not processed :sweat_smile: At least I am still getting the error that I need to send the registration codes...

**Comment by watchedsyncforkodi** [comment]
@AxaliaN That is strange - as of my earlier message the queue was cleared. Please double check the email address you sent it to.

**Comment by AxaliaN** [comment]
Hey,

I sent it to [redacted], is that no longer correct?

**Comment by watchedsyncforkodi** [comment]
Hi,

The email address was correct. I've redacted it above.

Your email was filtered as spam. That is why it was missed. Sorry
