### ISSUE TITLE
Kodi Profiles / Multi User Support?

### ISSUE THREAD

**Issue by jmh2002** [watchedsyncforkodi/service.watchedsync#3]
Kodi Profiles / Multi User Support?

Will the addon sync completely separately when using different Kodi Profile / User?

**Comment by watchedsyncforkodi** [comment]
Sorry the addon is unlikely to support multiple profiles. It currently uses the [VideoLibrary.SetMovieDetails](https://kodi.wiki/view/JSON-RPC_API/v10#VideoLibrary.SetMovieDetails) API to update the resume status. That API doesn't support specifying Kodi Profiles.
