### ISSUE TITLE
Is the email/verification system  still active? Fails in android.

### ISSUE THREAD

**Issue by rafi-d** [watchedsyncforkodi/service.watchedsync#9]
I'm not receiving any verification/response to sent emails... :( 
Edit : Got it...

**Comment by rafi-d** [comment]
Does not work in android (19.5 & 20.5) . 

```
2024-04-18 07:29:32.515 T:23471    INFO <general>: [service.watchedsync] Snapshot 2a
2024-04-18 07:29:32.515 T:23471    INFO <general>: [service.watchedsync] Snapshot 2b
2024-04-18 07:29:32.515 T:23471    INFO <general>: [service.watchedsync] Snapshot 2c
2024-04-18 07:29:32.515 T:23471    INFO <general>: [service.watchedsync] Snapshot 2d
2024-04-18 07:29:32.521 T:23471    INFO <general>: [service.watchedsync] Successfully registered device
2024-04-18 07:29:34.032 T:23471    INFO <general>: [service.watchedsync] Snapshot 3
2024-04-18 07:29:34.033 T:23471   ERROR <general>: [service.watchedsync] Failed client authentication during setup: Missing client_id
2024-04-18 07:29:34.034 T:23471    INFO <general>: [service.watchedsync] Snapshot 6
2024-04-18 07:29:34.034 T:23471   ERROR <general>: [service.watchedsync] Failed to complete setup correctly. Terminating service

```

[kodi - debug Copy (2).log](https://github.com/watchedsyncforkodi/service.watchedsync/files/15021955/kodi.-.debug.Copy.2.log)
[kodi - Copy.log](https://github.com/watchedsyncforkodi/service.watchedsync/files/15021956/kodi.-.Copy.log)

**Comment by rafi-d** [comment]
Update:
I have re-initialized  Kodi  one more time on both android boxes, and the status is now "connected".
One thing I can point out  - that these boxes have a very long initialization for Kodi (re-scanning the whole local folders). Maybe this has something to do with the issue?   Or just a slower first time initialization ?

One observation though: 
When changing the "watched" state manually - it works well and immediately, BUT if you check it with a real TV show video which completes "naturally" - it seems to fail to update the other clients after it completes playback , sometimes. When this happens,  it seems to update only on the next Kody startup. Is that the expected behavior?

One question: 
Is there a way to force a full sync for the whole library (I mean only the watched videos, not the un-watched ones...) - from one Kodi to the other Kodi boxes/clients? I am trying to sync everything (from before the addon was installed) to the two other Kodi clients. 

A "sync-all active/watched/in-progress" operation - can be useful for new installs. RE-marking each and every video is not do-able...

**Comment by watchedsyncforkodi** [comment]
> Update: I have re-initialized Kodi one more time on both android boxes, and the status is now "connected". One thing I can point out - that these boxes have a very long initialization for Kodi (re-scanning the whole local folders). Maybe this has something to do with the issue? Or just a slower first time initialization ?
> 

This is expected behaviour as the add-on will pause if library is being updated on startup. Under [Things to Note](https://github.com/watchedsyncforkodi/service.watchedsync?tab=readme-ov-file#things-to-note)

- The add-on will pause syncing while Kodi is playing a video or when the video library is being updated.

> One observation though: When changing the "watched" state manually - it works well and immediately, BUT if you check it with a real TV show video which completes "naturally" - it seems to fail to update the other clients after it completes playback , sometimes. When this happens, it seems to update only on the next Kody startup. Is that the expected behavior?
> 

If it updated on startup means the sync message was sent. I'd guess that Kodi wasn't idle. The add-on will pause syncing unless Kodi is idle. 

> One question: Is there a way to force a full sync for the whole library (I mean only the watched videos, not the un-watched ones...) - from one Kodi to the other Kodi boxes/clients? I am trying to sync everything (from before the addon was installed) to the two other Kodi clients.
> 
> A "sync-all active/watched/in-progress" operation - can be useful for new installs. RE-marking each and every video is not do-able...

This is on the "to do" list. A prerequisite would be implementing backup/restore functionality - see https://github.com/watchedsyncforkodi/service.watchedsync/issues/2

**Comment by watchedsyncforkodi** [comment]
Closing as original OP message complete.
